[build]
  publish = "public"
  #command = "npm run build" # sau orice altă comandă de construire necesară

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
