[build]
publish = "public"  # directorul în care se află fișierele statice

[[redirects]]
from = "/HTML/*"
to = "/HTML/:splat"
status = 200

[[redirects]]
from = "/CSS/*"
to = "/CSS/:splat"
status = 200

[[redirects]]
from = "/JS/*"
to = "/JS/:splat"
status = 200

[[headers]]
for = "/CSS/*"
[headers.values]
Content-Type = "text/css"

[[headers]]
for = "/HTML/*"
[headers.values]
Content-Type = "text/html; charset=utf-8"

[[headers]]
for = "/JS/*"
[headers.values]
Content-Type = "text/javascript"
